services:
  frontend:
    build:
      context: .
      args:
        - NEXT_PUBLIC_API_URL=http://api:3000/api
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://api:3000/api
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=your_nextauth_secret_here
    restart: unless-stopped
    # Add network configuration to improve stability
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
