name: Frontend CI/CD

on:
  push:
    branches: [main]
    paths:
      - "**/*.ts*"
      - "**/*.js*"
      - "Dockerfile"
      - ".github/workflows/*.yml"

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test --ci --watchAll=false

      - name: Build with test environment
        run: |
          cp .env.test .env.production
          yarn build

  docker-publish:
    needs: [build-test]
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/conduit-frontend:latest
            ghcr.io/${{ github.repository_owner }}/conduit-frontend:${{ github.sha }}
          build-args: |
            NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}
            NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}
